In [1]:
import numpy as np

print(np.__version__)

2.5.3


In [2]:
lista = [1, 2, 3, 4]
type(lista)

list

In [3]:
lista * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
lista / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [7]:
array = np.array([1, 2, 3, 4])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[1 2 3 4]


In [8]:
array * 2

array([2, 4, 6, 8])

In [9]:
array / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
array ** 2

array([ 1,  4,  9, 16])

### Cast de lista a numpy array

In [13]:
array = np.array(lista)
print(array)
print(type(array))
print(array.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [15]:
array_float = array.astype("float64")
print(array_float)
print(array_float.dtype)

[1. 2. 3. 4.]
float64


In [16]:
array_str = array.astype("str")
print(array_str)
print(array_str.dtype)

['1' '2' '3' '4']
<U21


### Tipos de array

In [17]:
# SCALAR
scalar = np.array(10)
print(scalar)
print(type(scalar))
print(scalar.ndim)
print(scalar.shape)

10
<class 'numpy.ndarray'>
0
()


In [18]:
# VECTOR
vector = np.array([1, 2, 3, 4])
print(vector)
print(type(vector))
print(vector.ndim)
print(vector.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


In [19]:
# MATRIZ
matriz = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print(matriz)
print(type(matriz))
print(matriz.ndim)
print(matriz.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)


### Generación de números

In [20]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.zeros(5, dtype="int64")

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((4, 6), dtype="float64")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((4, 6, 2), dtype="float64")

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.ones((5, 5), dtype="int64")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
vector_aleatorio = np.random.randint(0, 20, 5)
print(vector_aleatorio)

[10 19  4 15  1]


In [46]:
vector_aleatorio = np.random.randn(5, 2)
print(vector_aleatorio)

[[-0.25623248  0.23130935]
 [-1.17276118  0.58966379]
 [ 1.64836155  1.4584145 ]
 [ 0.15596534  1.29273291]
 [-0.68582171 -0.03238373]]


In [47]:
vector_aleatorio ** 2

array([[6.56550831e-02, 5.35040162e-02],
       [1.37536878e+00, 3.47703390e-01],
       [2.71709580e+00, 2.12697286e+00],
       [2.43251884e-02, 1.67115839e+00],
       [4.70351421e-01, 1.04870577e-03]])

In [48]:
vector_aleatorio.sum(axis=0)

array([-0.31048847,  3.53973684])

In [49]:
vector_aleatorio.sum(axis=1)

array([-0.02492313, -0.58309738,  3.10677605,  1.44869826, -0.71820544])

In [50]:
import time

lista = list(range(10000000))

def potencia(datos, exp=2):
    return [dato ** exp for dato in datos]

start = time.time()
potencia(lista)
end = time.time()

print(f"La funcion potencia en una lista demoro: {end - start}")

La funcion potencia en una lista demoro: 0.2401258945465088


In [51]:
array = np.array(lista)

start = time.time()
resultado = array ** 2
end = time.time()

print(f"La funcion potencia en una array demoro: {end - start}")


La funcion potencia en una array demoro: 0.00719904899597168
